[project]
name = 'Smart-Waste-Collection-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.bin-fill-telemetry]
path = 'contracts/bin-fill-telemetry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.contamination-enforcement]
path = 'contracts/contamination-enforcement.clar'
clarity_version = 3
epoch = '3.2'

[contracts.recycling-rewards]
path = 'contracts/recycling-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.route-planning-engine]
path = 'contracts/route-planning-engine.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
